on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      KOOL_DEPLOY_DOMAIN: ci.kool.dev

    steps:
    - name: Install Kool
      uses: kool-dev/action@v1

    - name: Checkout code
      uses: actions/checkout@master

    - name: Kool Deploy
      run: kool deploy
